name: actionlint

on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: ubuntu-latest

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: raven-actions/actionlint@v2
